### ISSUE TITLE
DevSkim crashes Visual Studio Code Extension service

### ISSUE THREAD

**Issue by ghost** [Microsoft/DevSkim-VSCode-Plugin#13]
On Visual Studio Code, installing DevSkim crashes the extension engine and you can not use any  other extension.

VSCode Insider-build 1.21.0

**Comment by joshbw** [comment]
I'll get a fix up Tuesday - sorry for the inconvenience!

**Comment by joshbw** [comment]
@codeprefect I'm a total liar, I pushed the fix today instead of tomorrow.  Version 0.2.2 is now live in the extension gallery.  Can you please validate that it addresses your problem (and not that I have found a completely different crashing problem and fixed that)?  Thanks for the feedback and help!

**Comment by scovetta** [comment]
LGTM on Win 10 / Insider 1.21.0.
