### ISSUE TITLE
DevSkim doesn't clear problems when file closed

### ISSUE THREAD

**Issue by gnowland** [Microsoft/DevSkim-VSCode-Plugin#8]
It appears that DevSkim doesn't clear it's output from the "Problems" pane when an active file is closed, leading to duplicate problem reports and general overwhelming spamming of the problems pane over the course of a day. 🤢

**Comment by joshbw** [comment]
Thanks @gnowland.  I'll get a fix out this week

**Comment by joshbw** [comment]
Clarification @gnowland - when you say "duplicate problem reports", are you seeing the same specific code issue appearing in the problem output multiple times, corresponding to each time the file is re-opened?  If so, can you tell me which version of VS Code and which platform you are using?  I do see that the problems aren't cleared out on file close, but when the file is re-opened I'm not seeing any redundant problems being erroneously added on top of the existing ones.

In terms of keeping the problems in that pane after the file is closed, would you be satisfied with a setting that controls whether or not they are cleared out?  The reason I don't remove them is because I received separate feedback asking for them to stick around, so a setting seems to be the best way to make it work for everyone

**Comment by gnowland** [comment]
Yes, setting seems like the best way to go. It'd be great if the entire problems pane (or even just individual problems and/or files) could be cleared manually, but I'm guessing I'll have to submit an issue report on the main VSCode repo for that functionality 😉 . **EDIT**: [Looks like someone got there first](https://github.com/Microsoft/vscode/issues/29169)

My "duplicate problems" have been stemming from looking at a file preview (such as a markdown preview) or a git diff.... the .git temporary file and/or the preview file get stuck in the problems pane with the same "problems" (obviously), but from looking at the settings just now i think i can probably ignore them through `devskim.ignoreFilesList`? Might be nice to have those dir's in by default 😝 ? Hahah, I think I may be asking too much...

Thanks for your prompt reply!

**Comment by joshbw** [comment]
Ah - that makes sense.  It should be pretty easy to just ignore the .git files (I don't think it makes much sense to run DevSkim on those - probably should have thought of that earlier.  I'll just add them to the default ignoreFiles setting so someone could override it if they really wanted).  I'll have to poke around to see what construct VS Code is using in constructing the preview files, but makes sense to automatically ignore those as well.  I'm testing a bunch of new functionality this week and once I'm pretty comfortable that there aren't *obvious* bugs in those I'll get 0.2.0 out on the marketplace with the additional ignores and the setting to kill problems once a file closes (though I am making an assumption that VS Code will make that reasonably easy...).  It'll be out hopefully tomorrow afternoon or early/mid next week depending on how much work it takes to clear problems (won't be getting much work done Friday and Monday).

In terms of a "clear problems" button for that pane, it would be great (I have a spell check extension because I suck at spelling, but it sucks at reporting none-issues - I would LOVE a "get rid of this nonsense" button) but as you point out that one is a bit outside my control

**Comment by gnowland** [comment]
Wow, many thanks for your dedication!! And yes, don't work too hard this weekend, enjoy the summer weather... and the eclipse!!! Thanks again for looking into this, if you're ever down in San Diego first round's on me.

**Comment by joshbw** [comment]
Happy to help.  Turns out it was super easy, so in the next release assigning: 

`"devskim.removeFindingsOnClose": true`

in settings will cause the findings for a file to be cleared out when the file is closed

**Comment by joshbw** [comment]
Ok - 0.2.0 is out with the above setting.  It should also catch when a file is the git original when doing comparisons, to prevent redundant errors.  Can be downloaded at https://marketplace.visualstudio.com/items?itemName=MS-DevSkim.vscode-devskim

Thanks for the suggestions, and please let me know if there are any other features that would make the extension more friendly to use
